export default interface UserArticle {
	id: number,
	title: string,
	slug: string,
	source: string,
	datePublished: string | null,
	section: string,
	description: string,
	aotdTimestamp: string | null,
	url: string,
	authors: string[],
	tags: string[],
	wordCount: number,
	commentCount: number,
	readCount: number,
	dateCreated: string | null,
	percentComplete: number,
	isRead: boolean,
	dateStarred: string | null,
	proofToken: string | null
}