export default interface UserArticle {
	id: number,
	title: string,
	slug: string,
	sourceId: number,
	source: string,
	datePublished: string | null,
	dateModified: string | null,
	section: string,
	description: string,
	aotdTimestamp: string | null,
	score: number,
	url: string,
	authors: string[],
	tags: string[],
	wordCount: number,
	readableWordCount: number,
	pageCount: number,
	commentCount: number,
	latestCommentDate: string | null,
	readCount: number,
	latestReadDate: string | null,
	userAccountId: number,
	wordsRead: number,
	dateCreated: string | null,
	lastModified: string | null,
	percentComplete: number,
	isRead: boolean,
	dateCompleted: string | null
	dateStarred: string | null
}